repair home text writer
front-end-by-rimantas/18-grupe-portfolio-daniels pull request #101
Opened 2020-10-16 08:18 UTC by mjankovskij

2020-10-16 08:37 UTC, legarifulin approved these changes, later dismissed

2020-10-16 08:37 UTC, KristijonasJurk submitted a review, later dismissed

2020-10-16 12:39 UTC, qReilas approved these changes

2020-10-16 13:40 UTC, qReilas submitted a review, later dismissed

2020-10-16 14:51 UTC, eimuc approved these changes, later dismissed

2020-10-17 09:14 UTC, legarifulin submitted a review, later dismissed

2020-10-18 08:24 UTC, belauzas requested changes
Labai keista, į `develop` keliauja GIT conflict nešantis PR... Tipo, norite sugadinti savo projektą?

Pamenam? Sakiau ir rodžiau: visų pirma iš `develop` į savo branch pasidarome PR, tada pas save išsitaisome visas klaidas ir tik tada turite teisę kurti PR į `develop`...

Dabartiniu atveju sakyčiau, jog tikrintojai neatsakingai pažiūrėjo į visą šitą (jei iš vis pažiūrėjo)... 🤔

2020-10-18 09:37 UTC, closed without merging