min height 10px, transition on scroll
front-end-by-rimantas/18-grupe-portfolio-daniels pull request #28
Opened 2020-10-09 15:07 UTC by mjankovskij

minimalus aukstis 10px conteiner.
Scrollinant juosta virsutine tures minimaliai animacijos.

2020-10-09 16:15 UTC, qReilas approved these changes, later dismissed

2020-10-10 09:06 UTC, KristijonasJurk approved these changes, later dismissed

2020-10-10 09:58 UTC, legarifulin requested changes

2020-10-10 09:58 UTC, legarifulin commented on css/about.css
> +    height: 200px;
sitas supisa mano koda :D

2020-10-10 10:11 UTC, legarifulin submitted a review, later dismissed

2020-10-10 10:12 UTC, KristijonasJurk approved these changes

2020-10-10 10:57 UTC, KristijonasJurk approved these changes, later dismissed

2020-10-10 19:14 UTC, eimuc approved these changes, later dismissed

2020-10-12 06:47 UTC, legarifulin submitted a review, later dismissed

2020-10-12 06:54 UTC, KristijonasJurk submitted a review, later dismissed

2020-10-12 07:08 UTC, legarifulin approved these changes

2020-10-12 07:09 UTC, KristijonasJurk approved these changes

2020-10-12 07:11 UTC, qReilas approved these changes

2020-10-12 07:11 UTC, eimuc approved these changes

2020-10-12 07:11 UTC, merged