Services update
front-end-by-rimantas/18-grupe-portfolio-daniels pull request #42
Opened 2020-10-10 20:24 UTC by eimuc

2020-10-11 09:26 UTC, legarifulin requested changes
Conflicta turi

2020-10-11 14:53 UTC, eimuc commented
> Conflicta turi

Sutvarkiau GAL :D

2020-10-11 17:29 UTC, legarifulin approved these changes

2020-10-12 06:50 UTC, qReilas approved these changes

2020-10-12 06:51 UTC, mjankovskij approved these changes

2020-10-12 07:02 UTC, merged