Header
front-end-by-rimantas/18-grupe-portfolio-daniels pull request #62
Opened 2020-10-12 13:36 UTC by mjankovskij

Event listeners for header, header media...

2020-10-12 15:09 UTC, belauzas requested changes

2020-10-12 15:09 UTC, belauzas commented on js/header.js
> +console.log(heightAbout, heightServices, heightWorks, heightClients, heightBlog, heightContact);
Į `develop` ir `master` branch neturėtų patekti kodas, kuriame yra palikta `console.log()`

2020-10-12 18:14 UTC, legarifulin approved these changes, later dismissed

2020-10-12 18:20 UTC, KristijonasJurk submitted a review, later dismissed

2020-10-12 19:25 UTC, KristijonasJurk approved these changes, later dismissed
LGTM

2020-10-13 06:51 UTC, legarifulin submitted a review, later dismissed

2020-10-13 06:53 UTC, eimuc approved these changes, later dismissed

2020-10-13 07:02 UTC, qReilas submitted a review, later dismissed

2020-10-13 10:23 UTC, closed without merging